# Generated by Django 5.2.9 on 2026-02-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacleaning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=dict)),
                ('domain', models.CharField(default='generic', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cleaning_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='datacleaning.cleaningreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
