# Generated by Django 5.2.9 on 2026-03-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Report', max_length=200)),
                ('domain', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('finance', 'Finance'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('generic', 'Generic')], default='generic', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('filtered_rows', models.IntegerField(default=0)),
                ('kpi_count', models.IntegerField(default=0)),
                ('insight_count', models.IntegerField(default=0)),
                ('narrative', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='kpi_engine.analysisresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
