# Generated by Django 5.2.9 on 2026-02-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preparation', '0003_cleaneddataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleanedDataset',
        ),
    ]
