from django.db import models
from Authentication.models import CustomUser
from data_preparation.models import Dataset
from django.core.files.base import File
import os


class CleanedDataset(models.Model):
    """
    Stores AI-prepared datasets generated by the Intelligent Cleaning Engine
    """

    original_dataset = models.ForeignKey(
        Dataset,
        on_delete=models.CASCADE,
        related_name="cleaned_versions"
    )

    # Django will store file in media/cleaned_datasets/
    file = models.FileField(upload_to="cleaned_datasets/")

    cleaned_by = models.ForeignKey(
        CustomUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    cleaned_at = models.DateTimeField(auto_now_add=True)

    # Profiling report (JSON generated by DataProfiler)
    cleaning_report = models.JSONField(default=dict)

    rows = models.IntegerField(default=0)
    columns = models.IntegerField(default=0)

    # -------------------------------------------------------
    # Helper: Save file correctly from a path
    # -------------------------------------------------------
    def save_file_from_path(self, file_path):
        """
        Attaches a physical file (created by pandas) to this FileField.
        """
        with open(file_path, "rb") as f:
            django_file = File(f)
            filename = os.path.basename(file_path)
            self.file.save(filename, django_file, save=False)

    def __str__(self):
        return f"Cleaned Dataset of {self.original_dataset.file_name}"


