# Generated by Django 5.2.9 on 2026-02-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_preparation', '0004_delete_cleaneddataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='cleaned/')),
                ('report_json', models.JSONField(default=dict)),
                ('domain', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('finance', 'Finance'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('generic', 'Generic')], default='generic', max_length=50)),
                ('quality_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=2)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_reports', to='data_preparation.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
