# Generated by Django 5.2.9 on 2026-02-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0005_remove_report_user_delete_dataset_delete_report'),
        ('data_preparation', '0004_delete_cleaneddataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cleaned_datasets/')),
                ('cleaned_at', models.DateTimeField(auto_now_add=True)),
                ('cleaning_report', models.JSONField(default=dict)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('cleaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.customuser')),
                ('original_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_versions', to='data_preparation.dataset')),
            ],
        ),
    ]
