# Generated by Django 5.2.9 on 2026-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningreport',
            name='ai_report_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
