# Generated by Django 5.2.9 on 2026-03-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacleaning', '0002_cleaningreport_ai_report_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningreport',
            name='ai_report_json',
        ),
    ]
